---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env
data:
  GEMINI_AI_MODEL: gemini-1.5-pro
  GOOGLE_API_KEY: your_api_key
  SONARQUBE_URL: http://localhost:9000
  SONARQUBE_TOKEN: your_token
  GITLAB_URL: http://localhost:9001
  GITLAB_TOKEN: your_token
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-suggestion
  labels:
    app: ai-suggestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-suggestion
  template:
    metadata:
      labels:
        app: ai-suggestion
    spec:
      containers:
      - name: ai-suggestion
        image: quay.io/jonkey/sonarqube-issue-ai-suggestion:1.1
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: env
---

apiVersion: v1
kind: Service
metadata:
  name: ai-suggestion
spec:
  selector:
    app: ai-suggestion
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ai-suggestion
spec:
  to:
    kind: Service
    name: ai-suggestion
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
